### ISSUE TITLE
Double chests split into 2 single chests

### ISSUE THREAD

**Issue by Sylvamy** [pop4959/LWCX#101]
**LWC Version (/lwc admin version):** 
2.2.5-67bdb89

**Server version (/version):** 
git-paper-211 1.15.2

**Short five word summary of issue:** 
Double chests change to single

**Detailed description of problem:**
Double chests change to single chests, locked or unlocked, only when lwc is installed

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by Sylvamy** [comment]
seems to have stopped for some reason

**Comment by pop4959** [comment]
Thanks for updating the issue. I don't think LWC would be doing this however, as it doesn't modify the world. It just keeps track of where the chests are. Might have been a random occurrence, or another plugin / the server.
