### ISSUE TITLE
Feature: One-time /cmodify

### ISSUE THREAD

**Issue by kakduman** [pop4959/LWCX#102]
**Short twelve-word summary:** 
Players could interact x times before losing access to a protected block.

**Detailed description of problem:**
Would it be possible to create a command similar to /cmodifylimit <#> that allows players to interact with a button, door, chest, etc. only a certain number of times before losing access to it? For chests, this would mean that the could open it this certain number of times and could remove as many items as they want each time.

It'd be nice if there was also a /cpubliclimit <#> to make it so any player could only interact with the block a specified number of times. A player on my server is looking to use this as a tool to ensure that all newbies get a free item by clicking a button, while making sure that nobody clicks the button too many times.

Example: If I want the player Notch to interact with my chest only 1 time, I could type /cmodifylimit 1 Notch, followed by right-clicking the chest. If I wanted Notch to interact twice, I could type /cmodifylimit 2 Notch.

Thanks for developing this plugin!

**Comment by pop4959** [comment]
Hey! Thank you for the feature suggestion. Unfortunately, I don't think this is something I want to have implemented in LWC, as the plugin's main responsibility is protecting blocks. I think that you are doing is best suited towards a kit plugin, or join plugin. There are dozens on Spigot, so I don't think you'll have any trouble finding something that does this! For example, even Essentials has a feature where a kit can be created that is given to newbies exactly once. Hope you find something good. 😄
