### ISSUE TITLE
Wiki:Command failure

### ISSUE THREAD

**Issue by Gu-f** [pop4959/LWCX#103]
**LWC Version (/lwc admin version):** 
**Server version (/version):** 
paper1.13.2
**Short five word summary of issue:** 
Command failure
**Detailed description of problem:**
No lock mode will disable automatic protection creation.
/cnolock - Turns on/off the no-lock mode
Alias of /lwc mode nolock
Echo display:That isn't a valid LWC command.

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
What version of LWC are you using? You happened to conveniently leave that out. The command is rather new, so you will need an up-to-date version of the plugin to use it.

**Comment by Gu-f** [comment]
Vsersion:Modern-LWC-2.1.5

**Comment by pop4959** [comment]
This repository is for [LWC Extended](https://www.spigotmc.org/resources/lwc-extended.69551/) (LWCX), not Modern LWC. That's why the command doesn't exist. Please update to the latest version, and it should work.
