### ISSUE TITLE
lwc.mod does not allow viewing private protections.

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#105]
Wiki states: Allows the player to open any LWC protection, but does not give them destructive powers such as being able to remove a protection or access to /lwc admin

This is not the case. Users with lwc.mod cannot open /cprivate'd chests.

**Comment by pop4959** [comment]
Cannot replicate. This is what I did, and it seems to be working as expected:

1) Protected chest as myself.
2) Had another user with no perms try to open the chest. It failed.
3) `/lp user <user> permission set lwc.mod`
4) Had them try opening again. Succeeded.

**Comment by andrewkm** [comment]
This is not working on our end. Definitely an issue.
I followed your exact steps using the latest LWCX dev build.

**Comment by andrewkm** [comment]
1. cprivate
2. click chest
3. alt user cannot open
4. /lp user alt permission set lwc.mod
5. alt user cannot open

Permission check being done on the alt account:
https://i.imgur.com/ysfkQ8c.png

**Comment by andrewkm** [comment]
Discussed over Discord.

**Comment by pop4959** [comment]
Turns out it's working, but is a bit strange. I may look into revamping lwc.mod in a future update (but no need to re-open this issue).
