### ISSUE TITLE
Multiple database errors

### ISSUE THREAD

**Issue by GriffinCodes** [pop4959/LWCX#109]
**Versions:** 
![image](https://user-images.githubusercontent.com/12417961/84348093-269ad180-ab82-11ea-9542-dd1220e581ec.png)

**Short five word summary of issue:** SQLExceptions appearing in console from time to time, not reproducible or consistent

**Detailed description of problem:**
[Stacktrace 1](https://paste.bnn.gg/ecehu.java)
![image](https://user-images.githubusercontent.com/12417961/84348166-47fbbd80-ab82-11ea-8bad-abc09cee9e2c.png)

[Stacktrace 2](https://paste.bnn.gg/kuxih.java)
[Stacktrace 3](https://paste.bnn.gg/sicaz.java)
[Stacktrace 4](https://paste.bnn.gg/ufehi.java) - Cause by trying to break a trap door

Cannot reliably reproduce, not sure what caused 2 & 3.

**Comment by pop4959** [comment]
I've had this problem reported to me before, although very rarely. No one has been able to figure out exactly how to cause it, but it seems to be related to the history feature. Do you use this? Try disabling history in the config, and let me know if you are still getting these errors or not.

**Comment by pop4959** [comment]
Closing for now, there isn't a way for me to replicate this currently.
