### ISSUE TITLE
Request:  Please add /cadmin forceowner command to list of things that /cpersist works on

### ISSUE THREAD

**Issue by mrcoffee1026** [pop4959/LWCX#118]
**LWC Version (/lwc admin version):** 
2.2.6-2d10269
**Server version (/version):** 
1.15.2-1.16.1

**Short five word summary of issue:** 
The /cpersist command is beyond critical for bulk updating, but it would be nice if it would extend to admin level commands as well such as /lwc admin forceowner <player> as redoing this for every item... even with the arrow key... is excessively tedious when you have a lot to transfer.

**Comment by pop4959** [comment]
I'd be surprised if it doesn't already, but I won't say I've tried it. Good idea though, I'll look into it. By the way though, there is a `/lwc admin forceownerall` command if you need to transfer *all* protections to another user. Just worth mentioning in case that is what you're trying to do.

**Comment by mrcoffee1026** [comment]
It absolutely does not already, I have attempted it.  And no I would never have a case where I'd want to transfer ALL to another player.  This came up because moving the data from mysql to sqlite was impossible.  Tried several times and the results were always some sort of unpredictable failure where some items kept their locks, some items did not, still others could not be re-locked ever, their previous positions being toxic to this plugin forevermore, so the only option was to clear the db and start from scratch which leaves everything unlocked.  As an admin I can wander around relocking things but have no method of selecting a group of locked items to a new player, there's just everything I've EVER locked, which I'd never want to use... or a single one.  This works, but as I said, is very tedious.  using cpersist here has no effect... in fact if i use cpersist it just uses the last command i used - /cprivate - INSTEAD of /cadmin forceowner otherplayer, so cpersist is in no way compatible with this admin command.

**Comment by pop4959** [comment]
Yeah it was probably an oversight by the original developer of LWC. It makes sense for a command like this one to persist, so as mentioned, I'll take a look into it. I'd imagine it can't be too difficult to add support for it given how the system works.

**Comment by mrcoffee1026** [comment]
cool, thanks much!

**Comment by pop4959** [comment]
Latest dev builds add the `owner:` type modification for `/cmodify` which appears to work just fine with cpersist.

E.g. `/cpersist` -> `/cmodify owner:pop4959` -> click on a bunch of stuff.

Of course, cmodify can only be run by an admin or the owner of the protection.
