### ISSUE TITLE
Server crash on /cremoveall command

### ISSUE THREAD

**Issue by Thefirstalpha** [pop4959/LWCX#121]
**LWC Version (/lwc admin version):**2.2.6-2d10269 
**Server version (/version):** git-Paper-135 (MC: 1.16.1)

**Short five word summary of issue:** 
Server crash on /cremoveall command

**Detailed description of problem:**
When a player that has a lot of chest use /cremoveall, the server crash. I think the first useful thing will to have the possibility to make permission on that, like allow to use cremove but not cremoveall for lambda player.
Seconde part will to find a solution to make this command more efficient ^^

**If there was an error in console, put it here:**
```
[INFO] Reyti44 issued server command: /cremoveall
[INFO] Reyti44 issued server command: /lwc confirm
[ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-135 (MC: 1.16.1) ---
[ERROR] The server has not responded for 10 seconds! Creating thread dump
[ERROR] ------------------------------
[ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
[ERROR] ------------------------------
[ERROR] Current Thread: Server thread
[ERROR]     PID: 24 | Suspended: false | Native: true | State: RUNNABLE
[ERROR]     Stack:
[ERROR]         app//org.sqlite.core.NativeDB.step(Native Method)
[ERROR]         app//org.sqlite.core.DB.execute(DB.java:849)
[ERROR]         app//org.sqlite.core.DB.executeUpdate(DB.java:902)
[ERROR]         app//org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[ERROR]         com.griefcraft.sql.PhysDB.removeProtection(PhysDB.java:1839)
[ERROR]         com.griefcraft.model.Protection.remove(Protection.java:840)
[ERROR]         com.griefcraft.modules.free.FreeModule$1.run(FreeModule.java:250)
[ERROR]         com.griefcraft.model.ConfirmAction.onConfirm(ConfirmAction.java:48)
[ERROR]         com.griefcraft.modules.confirm.ConfirmModule.onCommand(ConfirmModule.java:70)
[ERROR]         com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:367)
[ERROR]         com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:191)
[ERROR]         app//org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[ERROR]         app//org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[ERROR]         app//org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[ERROR]         app//net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910)
[ERROR]         app//net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721)
[ERROR]         app//net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[ERROR]         app//net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[ERROR]         app//net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[ERROR]         app//net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5435/0x000000080225b440.run(Unknown Source)
[ERROR]         app//net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[ERROR]         app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[ERROR]         app//net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[ERROR]         app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[ERROR]         app//net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137)
[ERROR]         app//net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130)
[ERROR]         app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[ERROR]         app//net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091)
[ERROR]         app//net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[ERROR]         app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[ERROR]         app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3025/0x0000000801323840.run(Unknown Source)
[ERROR]         java.base@14.0.2/java.lang.Thread.run(Thread.java:832)
```

**Comment by pop4959** [comment]
How many protections was this? Is the server running on an SSD? Just curious. Either way, I'll check into this.

**Comment by pop4959** [comment]
Oh yeah, as a workaround for the time being, if you want to remove the command from your server, add the following alias to [commands.yml](https://bukkit.gamepedia.com/Commands.yml):

`  - cremoveall: []`

**Comment by Thefirstalpha** [comment]
Ok thanks for the tips :)
There is more than 1000 for this player, but I correct what I said, it also appears for player that only have 200 protections, and we use the SQLite Databases

**Comment by pop4959** [comment]
> Ok thanks for the tips :)
> There is more than 1000 for this player, but I correct what I said, it also appears for player that only have 200 protections, and we use the SQLite Databases

Yes but what disk? I don't think 1000 protections will normally take over 10 seconds on SQLite. The server might be running on a hard drive instead of a solid state drive storage medium. SQLite benefits hugely from faster storage.

**Comment by Thefirstalpha** [comment]
Yes it's an SSD, our provider only give the information that is an SSD
I've also checked in the Linux configuration with that method https://unix.stackexchange.com/questions/65595/how-to-know-if-a-disk-is-an-ssd-or-an-hdd
And this step to get read and write speed test https://www.shellhacks.com/disk-speed-test-read-write-hdd-ssd-perfomance-linux/
Read: copied, 2,00228 s, 536 MB/s
Write: copied, 2,18164 s, 492 MB/s

The problem also appears with another player that only has 200 protection, but it's a very old player, so maybe it's because his protections are "far away" in the DB, that browsing all the DB can maybe take a lot of time?

A solution can maybe to limit the removeall to only remove by the amount of 100 protections at the same time from here https://github.com/pop4959/LWCX/blob/6df92042b93f0f977f56dfb8506e5d2a7bfcdba2/src/main/java/com/griefcraft/modules/free/FreeModule.java#L247-L248 with an argument in loadProtectionsByPlayer() to only take the first X amount of protection, and while it still contains protection, adding a schedule task to make the rest 5 tick later ?

**Comment by pop4959** [comment]
I've added an optional permission `lwc.removeall` for this in the latest dev builds. I haven't seen anyone else complaining about this, so this is probably _good enough_ right now.

Don't really feel like writing a workaround for this, since it's the same old performance issue that LWC tends to have.. It would be better to completely rewrite the database handler, which would be a much larger endeavor.
