### ISSUE TITLE
Issue with /cpublic and double doors in protected regions

### ISSUE THREAD

**Issue by sh1mrr4** [pop4959/LWCX#125]
**LWC Version (/lwc admin version):** 

2.1.5-09ad392

**Server version (/version):** 

Paper 1.15-378

**Short five word summary of issue:** 
Double doors with /cpublic open partially, even if interaction is denied by another plugin

**Detailed description of problem:**

If a double door is inside a protected region (like WorldGuard or Towny), but has /cpublic on it, it can still be opened by players without access to that region. Essentially, the protection plugin successfully blocks the interaction with the door the player is clicking, but before that the second door of the pair opens because of LWC (which is not prevented by the protection plugin).

I know this is a very specific issue, but I wanted to let you know regardless (if it hasn't been reported prior). Thanks a lot :)

**Comment by pop4959** [comment]
@sh1mrr4 Can you make sure this is still a problem on the [latest version of LWC](https://www.spigotmc.org/resources/lwc-extended.69551/)? Modern LWC is not supported anymore & you are over a year out of date.

**Comment by sh1mrr4** [comment]
Woops, I didn't even check when the last update was. Thanks for keeping the plugin alive though!

I now tested with version 2.2.6-2d10269 and the issue still occours.

**Comment by Xaver106** [comment]
Still an issue with 2.2.7-ad0f824
LWC doesn't seem to check if another plugin is blocking the interaction and just opens the door.

**Comment by pop4959** [comment]
@sh1mrr4 @Xaver106 Hey, finally got a chance to look into this. Should be fixed by b7b3af198b754b6b5976caa54073703a6e8befa3. Check out the latest dev builds and let me know if it seems to be working properly now.
