### ISSUE TITLE
Command to "handover" a protection to a different Player

### ISSUE THREAD

**Issue by masterX244** [pop4959/LWCX#127]
**Detailed description of problem:**
There should be a command where the owner can "handover" the protection so the target player is the new owner. Like /lwc admin forceowner but restricted to own protections only.

Would be useful for Players that drop off a delivery of stuff to someone who is off atm without leaving unprotected chests

**Comment by pop4959** [comment]
Latest commit b04643f6ef1e3d2b5eeefe81e96c87e3f67292ad adds the `owner:` modification type.

For example `/cmodify owner:pop4959`
