### ISSUE TITLE
LWC Admin Cleanup doesn't cleanup blocks replaced with another block.

### ISSUE THREAD

**Issue by FireController1847** [pop4959/LWCX#128]
**LWC Version (/lwc admin version):** 2.2.6-2d10269
**Server version (/version):** git-Paper-231 (MC: 1.16.3)

**Short five word summary of issue:** LWC Admin Cleanup doesn't cleanup blocks replaced with another block.

**Detailed description of problem:**
Instead of describing, let's just jump straight to reproducing:
1. Place a protected block
2. Stand on top of that block, and run `/setblock ~ ~-1 ~ oak_planks`
3. Run `/cinfo` and observe that the block is still protected (expected behavior)
4. Run `/lwc admin cleanup` and wait for it to finiah
5. Run `/cinfo` on the same block and observe that it is still protected, even though it no longer is there or the same matching type

This issue is major because when using plugins such as CoreProtect, upon reverting grief many protected blocks will be replaced with their previous state (for example, some oak planks). LWC Admin Cleanup doesn't remove the protections, however, so the player still has to deal with whatever we needed to revert being protected and destroyable.

**Comment by pop4959** [comment]
As far as I know, this is normal behavior with plugins that directly modify blocks in the world without triggering a block break/place. Cleanup should work, however, unless the block that got replaced is another protectable block. Make sure that wood planks are not in your blocks list in the core.yml config.

**Comment by FireController1847** [comment]
I am certain that it is not in my `core.yml`. It first protected `spruce_planks`, then I attempted it with `stone`, `oak_wood`, and `oak_logs`. The issue appears for all of these items yet none of them are in my `core.yml` (or any of the other yml files for that matter).

**Comment by pop4959** [comment]
Can you share your core.yml? I'll try using the same one when I try to replicate this.

**Comment by FireController1847** [comment]
[core.yml.txt](https://github.com/pop4959/LWCX/files/5434148/core.yml.txt)

Sorry GitHub won't let me upload a .yml so you'll need to remove .txt

**Comment by FireController1847** [comment]
[core.yml.txt](https://github.com/pop4959/LWCX/files/5434149/core.yml.txt)

Let's err... not share that password with anyone (referring to the fact I panic deleted my previous post). Sorry I had to send as .txt not .yml GitHub won't let me upload .yml for some weird reason

**Comment by pop4959** [comment]
Confirmed. It seems like the cache was not being properly updated by cleanup, and in some cases, the protection was being flushed back into the database.

Should be fixed in fbbc9172e7c4fc92f79246a89196e2497964dd13, and development builds are available and linked on the plugin page.
