### ISSUE TITLE
Groups not working on  /cdisplay

### ISSUE THREAD

**Issue by masterX244** [pop4959/LWCX#132]
**LWC Version (/lwc admin version):** 
2.2.6-2d10269
**Server version (/version):** 
git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
**Short five word summary of issue:** 
Groups not working on  /cdisplay
**Detailed description of problem:**
Players from a LuckPerms group cannot take items out of a Display container if they are /cmodified to the chest. If added by player name it is possible though

**If there was an error in console, put it here:**

**Comment by pop4959** [comment]
Does this happen with donation chests as well? They should be pretty similar.

**Comment by masterX244** [comment]
yes, happens on donation chests, too

**Comment by pop4959** [comment]
@masterX244 This should be fixed on the latest development build of LWC, which you can find linked on the plugin page.
