### ISSUE TITLE
LWC Commands Invalid

### ISSUE THREAD

**Issue by koutarou28** [pop4959/LWCX#134]
**LWC Version (2.2.6):** 
**Server version (Spigot 1.16.3):** 

**LWC Commands Invalid:** 

**Installation of LWCX 2.2.6 into Spigot Plugins folder currently housed on a MAC Mini was unsuccessful.
   Restarted server and saw during boot logs that LWC was successfully started, however upon login and attempting to place a block no notification of protection was provided. I followed the wiki to op myself in order to administer the plugin and provide specific rights to staff, however all /lwc commands fail. I cannot even verify anything by typing /lwc info, or any other /lwc command. every command says in dark red "That is not a valid LWC Command"

I have double checked all of the configs and even attempted removal of all other plugins to no avail.
I use Vault as well as LuckPerms and essentials.
Could I have this looked into? if there is any additional information needed, please let me know.

![2020-11-26_21 35 24](https://user-images.githubusercontent.com/43107808/100414811-7e919b80-302f-11eb-9071-700e5d82f045.png)
Thank you.

**Comment by pop4959** [comment]
Installed a fresh server with the latest Paper as of writing (#298) and LWC 2.2.6. Commands and protections are working.

Not sure if this could be because of Spigot (unlikely, as I would probably have a lot of reports by now) or the Mac Mini. Perhaps you can try the install on a traditional system as well and see if you have the same results.

Also might be helpful to see the output of `/lwc admin report`.

**Comment by koutarou28** [comment]
LWC Report: 
Version: 2.2.6
Running time 23 hours 13 minutes 57 seconds ago
Players 3/50
Item entities: 16/1047
Permissions API: VaultPermissions

==Modules==
Engine: SQLite
Protections: 0
Queries: 308 | 0.00 / second

==Cache==
Usage 0.00% (0/10000 [10000+01])
Profile:
isKnownNull:470.746 (5.63 / second)
getProtection: 41.938 (0.50 / second)
addKnownNull: 25.254 (0.30 / second)

**Comment by koutarou28** [comment]
The issue was a plugin called PowerRanks. 
It is incompatible with LWC-X so I removed it.
