### ISSUE TITLE
Towny method used in LWC now deprecated.

### ISSUE THREAD

**Issue by Momshroom** [pop4959/LWCX#137]
**LWC Version (/lwc admin version):** 
Tested both in 2.2.6 AND 2.2.7 build 151 (from the paper site)
lwc admin version in 2.2.6 outputs: 2.2.6-2d10269
I already reverted from 2.2.7, so don't know on that one.

**Server version (/version):** 
git-Paper-331 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
Using deprecated towny method.

**Detailed description of problem:**

LWC warns that it's using a deprecated towny method on startup.
I'm using Towny version 0.96.5.6.

**If there was an error in console, put it here:**
```
[12:59:58 WARN]: [LWC] "LWC v2.2.7-dev-fbbc917" has registered a listener for com.palmergames.bukkit.towny.event.TownUnclaimEvent on method "public void com.griefcraft.modules.pluginsupport.Towny.onTownUnclaim(com.palmergames.bukkit.towny.event.TownUnclaimEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Hidendra, pop4959, Me_Goes_RAWR].
```

**Comment by pop4959** [comment]
Thanks for reporting, I'll check into this when I get time. I think the "Server performance will be affected" may not be accurate though, as I think this is just what is printed when any event usage is deprecated.

**Comment by Klawdek** [comment]
I am seeing the same warning.  I am using git-Paper-413 (MC: 1.16.4) and LWC version 2.2.6-2d10269

**Comment by pop4959** [comment]
Should be fixed in the latest development builds + next release.
