### ISSUE TITLE
Can't take book out of lectern when you are added via group

### ISSUE THREAD

**Issue by masterX244** [pop4959/LWCX#138]
**LWC Version (/lwc admin version):** 
Main plugin: 2.2.7-dev-fbbc917/ 
**Server version (/version):** 
This server is running Paper version git-Paper-332 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
Can't take book out of lectern when you are added via group
**Detailed description of problem:**
Taking a book out of a lectern fails when you are granted access via a group and not individually

**Comment by RedstoneFuture** [comment]
I can confirm this issue:

* **private + using of group:** Other people can only read the book **(!)**
* **private + using of name:** Other people can read, get and set the book **(!)**

* public lectern: Other people can read, get and set the book
* private lectern: Other people haven't the permission to the lectern

LWC 2.2.6-2d10269, PaperMC 1.16.4

**Comment by pop4959** [comment]
Thanks for confirming. I think this may require a similar fix as was done recently with 5694baa0d788a1456a962f0971e4e82036b8b2d3. I can look into it later this week if no one else has found a solution by then.

Happy holidays to both of you 😃

**Comment by RedstoneFuture** [comment]
Same with `2.2.7 #150`

**Comment by pop4959** [comment]
Sorry for taking so long to get around to this, but should be fixed in ab486558d4c84413414ce507925007bd3157f3b6. Tested with all of the cases @RedstoneFuture listed + display lectern. The checks are made in the same fashion as was done in 5694baa0d788a1456a962f0971e4e82036b8b2d3.
