### ISSUE TITLE
lwc Flushing protection updates causes long shutdown time

### ISSUE THREAD

**Issue by jordanwilliams1** [pop4959/LWCX#140]
https://i.gyazo.com/4599e8638b557c39d00613eca9eda035.png

Why is this flushing during a server shutdown? Shouldn't it be doing this async while the server is running? This is causing my shutdown time to take 20mins+ I Don't understand why in earth this would be done on a server shutdown.

I Run 100s of plugins and this is the only plugin acting up on shutdown.

**Comment by pop4959** [comment]
Already answered on Discord. This behavior indicates that you have a database issue, which you should probably investigate.

**Comment by jordanwilliams1** [comment]
@pop4959 This only happens when the servers tps gets really bad while the server is running. All my other plugins dont have a problem. I Run over 120 plugins. LWC Usually runs fine. It only dose this when the TPS has been low for 2 hours+

For instant my tps was below 10 for around 2 hours today. then during server shutdown it had to flush these. Why would the server lagging effect LWC tho?? It should be doing this async and shouldn't matter if the server itself is lagging.
