### ISSUE TITLE
Towny Ruined Compatability

### ISSUE THREAD

**Issue by lukemango** [pop4959/LWCX#143]
**LWC Version (/lwc admin version):** 2.2.6-2d10269
**Server version (/version):** 1.16.5 - Tuinity 1d169e7

**Short five word summary of issue:** 
We need towny ruined compatability

**Detailed description of problem:**
The town process goes as follows:
New town is made
_If bankruptcy is enabed: Town is goes bankrupt (town bank goes into negatives)_
Town gets put into 'ruined' because of they hit their debt cap (bankruptcy) or it gets disbanded (/t delete)
The town goes into a 'ruined' state for a configurable length, in which players can raid and break the town. LWC claimed blocks remain locked when they shouldn't.
After the ruined state, the town is deleted where LWC will then unlock the claimed blocks.

I believe a fix for this would be to add support for a town going into a ruined state with the Towny API, and removing LWC locks when this fires for the town.

**Note** IIRC Towny ruined states are disabled by default, enabled it in towny's config.yml @ town_ruining.town_ruins.enabled
**Process to make a ruined town:**
/t new (name)
/t delete (name)
(Ruined state will begin)

**Comment by wm-b** [comment]
I'm having the same problem. On my server, LWC also doesn't remove protections when a town chunk is unclaimed either via "/town unclaim", "/plot unclaim" or "/town delete".  This is with both of the towny integration options turned on in the towny.yml config.

**Comment by pop4959** [comment]
If anyone would be willing to put in a PR to add this functionality, please feel free to do so. I'll otherwise try to look into this when I find time, although I'm not an expert with Towny (last time I actively used it was around 2012) so it might take me some time to figure out.

**Comment by pop4959** [comment]
LlmDl (the lead Towny developer) himself took the time to implement this in f57d85cb4b7744e6fec19f68db444fba37b56737. Please give him your thanks!
