### ISSUE TITLE
Autoclose Flag for Trapdoors.

### ISSUE THREAD

**Issue by mare-on** [pop4959/LWCX#145]
**LWC Version (/lwc admin version):**
2.2.6

**Server version (/version):**
Paper 1.16.5-496

**Short five word summary of issue:**
Enable Autoclose flag for Trapdoors.

**Detailed description of problem:**
I have added trapdoors in protected blocks and I can easily lock them. I would like to set them autoclose like for doors or fence gates, but this flag is seems to not be supported by trapdoors.

**If there was an error in console, put it here:**
No errors.

**Comment by pop4959** [comment]
I was fairly certain this works, but I guess I'll have to take another look at it. If you can, please double check to see if this isn't a problem with some other plugin installed alongside LWC or that your config looks correct. If you can, please also share what config you're using for doors.

**Comment by mare-on** [comment]
Hi, thanks for the reply, I have re-tested it in every case and I realized where is the problem...

The flag is working correctly, I just didn't realized that I have my trapdoor placed in that way where it looks like they are closed while they are open. :D To fix my issue there should exists new flag "autoopen" that would be awesome ;)

**Comment by pop4959** [comment]
I'll change this to enhancement. The only problem I see is that with an auto-open flag if you have both the auto-open and auto-close flags, it might get set into a cycle repeatedly.

**Comment by mare-on** [comment]
Oh yeah, that would be a problem, maybe one condition with notification to player could be enought to prevent infinite cycle?
Something like... "Autoclose flag was detected and was removed due to autoopen flag applied."
