### ISSUE TITLE
[Javadoc] Improve documentation

### ISSUE THREAD

**Issue by Andre601** [pop4959/LWCX#149]
**LWC Version (/lwc admin version):** N/A
**Server version (/version):** N/A

**Short five word summary of issue:** Improve Javadoc comments of LWC

**Detailed description of problem:**
Looking at the [LWC class'](https://github.com/pop4959/LWCX/blob/master/src/main/java/com/griefcraft/lwc/LWC.java) Javadoc comments can I say that it's... acceptable at best.
The docs don't explain any parameters, nor do they even give a proper return description.

I would like to offer myself now to improve the Javadoc to be much more descriptive because those Bukkit-level of documentation is clearly nothing good to have and should be improved.

If you have any specific requirements in terms of overall Javadoc styling, let me know, so that I can include it into the possible PR.

**If there was an error in console, put it here:**
```
N/A
```

**Comment by pop4959** [comment]
Already discussed on Discord but please feel free -- I don't really have the desire nor time to do this myself. Least I can do is review the diff though if you're willing to put in some effort for this.

Just as a reminder, please try to keep docs changes and any code changes separate if possible. Multiple PRs is fine and preferable if they cover different classes / areas of the code.

**Comment by Andre601** [comment]
I (understandably) lost my interest in doing this after spending 6+ hours on it and not even getting like 50% done...

If you or anyone is curious can you see a diff in the changes I made so far here:
https://github.com/Andre601/LWCX/commit/900d190394a5895232799619cde3bb01be305ece

If I'm bothered enough will I perhaps return to this in the future... But for now, I really lost motivation and want to keep my sanity intact.

**Comment by pop4959** [comment]
Wise choice imo
