### ISSUE TITLE
Autoopen flag

### ISSUE THREAD

**Issue by mare-on** [pop4959/LWCX#150]
Hi, is there any chance for adding "autoopen" flag as negation of "autoclose" flag?

**Comment by pop4959** [comment]
I believe you already have an issue open for this (#145). It's possible that we can add this but it hasn't been added yet. The latest plugin release was made to address a critical issue with the MySQL DB adapter on newer Paper servers.

**Comment by mare-on** [comment]
Hi, yes, I already have this issue as open but with no more answers for more than a month so... where is the problem with something so simple like that? The latest release looking well, a lot of fixes for... I believe... critical issues but hey, that's not a reason to not-communicate in case of other issues.

**Comment by pop4959** [comment]
If this is urgent for you, please consider making a pull request. I can't promise if and when I will have time to add this. Thanks :)

**Comment by mare-on** [comment]
So what about a little help... for my needs I currently just added new **ENUM** type `AUTOOPEN` in class **Flags** and added new if condition in class **DoorsModule**.

Modified line **138**:

`if (action == Action.OPEN_AND_CLOSE || protection.hasFlag(Flag.Type.AUTOCLOSE) && !protection.hasFlag(Flag.Type.AUTOOPEN)) {`

Added if condition after previously condition:
```
if (action == Action.OPEN_AND_CLOSE || protection.hasFlag(Flag.Type.AUTOOPEN) && !protection.hasFlag(Flag.Type.AUTOCLOSE)) {
    final Block finalBlock = block;
    final Block finalDoubleDoorBlock = doubleDoorBlock;
    int wait = getAutoCloseInterval() * TICKS_PER_SECOND;

    lwc.getPlugin().getServer().getScheduler().scheduleSyncDelayedTask(lwc.getPlugin(), () -> {
        changeDoorStates(true, finalBlock, finalDoubleDoorBlock);
    }, wait);
}
```

It's not perfect but with **OP** I can use it for my needs. I don't want to scan the whole code because there is a lot of packages but the basic point and **protection** from **cycle** if both **autoopen** + **autoclose** flags are active.

**Comment by pop4959** [comment]
Yeah that sounds like it should work just fine. If both flags are applied you should probably block it to prevent a cycle.
