### ISSUE TITLE
Better color code support (including hex)

### ISSUE THREAD

**Issue by Sikatsu** [pop4959/LWCX#151]
**Short five word summary of issue:** 

Since 1.16 supports hexcodes, I am changing the color scheme of the server. I am able to do all plugins except LWC, it would be really nice if hex would be possible to support! ^^

Something like %hex% or {#hex}

**Comment by pop4959** [comment]
The latest dev build adds support with the `%#RRGGBB%` formatting placeholder. You can find it on [CodeMC](https://ci.codemc.io/view/Author/job/pop4959/job/LWCX-dev/).

An example:

```
public=%#7851a9%Public
private=%#FF69B4%Private
password=%#A52A2A%Password
```

![image](https://user-images.githubusercontent.com/17698576/118081789-e6833680-b370-11eb-9a59-bc97382cb8d2.png)
