### ISSUE TITLE
Towny - Non-Members Able To Lock

### ISSUE THREAD

**Issue by MarkThePanda** [pop4959/LWCX#153]
LWC Version 2.2.7
Server Version 1.16.5, Purpur #1117
Towny Version 0.97.0.0

Towny - Non-Members Able To Lock

When lockable items are not registered, players that are not apart of a town can lock lockable items inside a town. For example, an outsider that is not apart of my town can do /cprivate, preventing players inside of the town from interacting, or even removing the locked items.

In order to replicate this issue, one player shall create a town. Do /t new (name). The towny mayor should place a chest that is not registered. Now on another account that is not added to the town, do /cprivate on the chest. This should not occur, non-members should not be able to to claim stuff inside a town. 

Needed support for Towny integration.

**Comment by pop4959** [comment]
Changed the behavior in 842f3fcded7771878f484fcdd18821a7e3b8aed3 so that non-members are not able to register protections (this was previously only possible if you enabled the `townBorders` option).
