### ISSUE TITLE
Redstone not opening doors

### ISSUE THREAD

**Issue by AGuyNamedJens** [pop4959/LWCX#155]
**LWC Version (/lwc admin version):** 
2.2.7
**Server version (/version):** 
git-paper-731 (MC: 1.16.5)
**Short five word summary of issue:** 
Redstone doesn't open doors
**Detailed description of problem:**

So i'm trying to get Redstone (only by the person that has access to the door) to open the door. As well as close it.
What i'm experiencing however is that with the flag redstone **on** EVERYONE can open it. With the flag redstone **off** EVERYONE can close it.

Is this normal? I'd love to see a way to allow players with access to open/close using redstone, rather than everyone.. Thanks

**If there was an error in console, put it here:**
```
No
```

**Comment by pop4959** [comment]
Hey, thanks for the question. The `denyRedstone` option in the [configuration](https://github.com/pop4959/LWCX/wiki/Configuration) determines the default behavior of the flag (whether redstone is allowed or not until applied). It is normal that this applies to everyone accessing the protection. Unfortunately it is not possible for LWC to restrict redstone to specific players on specific protections.

**Comment by AGuyNamedJens** [comment]
Why is it not possible? Sad.. So basically it's just either allow everyone no matter protection being provate, or don't make it function at all..?

**Comment by pop4959** [comment]
It's because it's not possible to track redstone to a specific player (at least trivially, I'm sure it can be done somehow but that would be the job for another dedicated plugin to handle).

The redstone flag is meant to prevent the protection from being modified by redstone, and that's it. The access levels (public, private, display, etc) are for players that are opening the container, and have nothing to do with redstone.

**Comment by AGuyNamedJens** [comment]
Sad, alright then i guess the use of redstone flag should be off forever

**Comment by pop4959** [comment]
It depends on the type of server you're going for, but in your case that may be a good solution right now. I can't think of any plugins that let you control redstone flow per player.

**Comment by AGuyNamedJens** [comment]
It's just a community server i have for a group of friends, they want pressure plates on their doors so they wouldn't have to press the door when running from MythicMobs but i just told them to use the autoclose flag on the door and only open the door, which works fine. Thanks though!

Also i do remember lockette used to have that with buttons, it would just check if the player that pressed the button (to open the door) has access to that door.

**Comment by pop4959** [comment]
Ah okay, glad to hear! And yeah, like I mentioned above, the "trivial" redstone could be easy to check, but for example complicated redstone contraptions definitely not. Currently LWC just doesn't check anything though (except if the block allows redstone with the flag).

**Comment by AGuyNamedJens** [comment]
What do you mean with complicated redstone contraptions, like a full on key hopper system? I'm just asking a button or pressure plate next to the door to check if the player can access that door otherwise don't let the door open lol

**Comment by pop4959** [comment]
Something like that, yes 😛 

Either way, probably not something we're looking to add into LWC right now. If you're looking for something like Lockette, BlockLocker also exists (and it has a redstone sign, although I think it works similarly to this plugin).

**Comment by AGuyNamedJens** [comment]
Alright that's fine to me lol, my friends should just stop using redstone for doors if they want to protect it.

And yeah BlockLocker doesn't seem to check permissions, they state "Redstone contraptions cannot open protected doors, unless a [Redstone] tag is added." Rip.
