### ISSUE TITLE
behavior of redstone flag

### ISSUE THREAD

**Issue by RedstoneFuture** [pop4959/LWCX#159]
**LWC Version (/lwc admin version):**  2.2.7
**Server version (/version):**  1.16.5 PaperMC #771

**Short five word summary of issue:** 

uncoordinated behaviors with the redstone flag - tested on doors

**Detailed description of problem:**

I've tested the redstone protection flag with the default LWCX configuration. Based on the config option I activated redstone globally and deactivate it with `/lwc flag redstone on`. Basically, the flag works, but in some situations in my test the door opened or closed without any reasons. Check out the short videos I've made. (The biggest problem is that I can't demonstrate when I interact with the doors. But in most cases I didn't right-clicked on them.)

https://redstoneworld.de/videos/intern/lwcx_redstone_1.mp4
https://redstoneworld.de/videos/intern/lwcx_redstone_2.mp4

```
    # If true, the default behaviour will be to BLOCK redstone to protections, and /credstone on (Protection Flag)
    # will ALLOW redstone to the protection
    # If false, the default behaviour will be to ALLOW redstone to protections, and /credstone on will
    # BLOCK redstone to the protection
    denyRedstone: false
```

I down't need this flag for my server. This is only a note and maybe someone knows a reason / solution for this.

**If there was an error in console, put it here:**
```
-
```

**Comment by pop4959** [comment]
I haven't been able to reproduce this bug, and since there haven't been any other reports I will assume it might have to do with other plugins or such. Either way, probably not something that will be fixed (if toggling the `denyRedstone` option and the redstone flag doesn't fix it).
