### ISSUE TITLE
Feature Request :: Persist cnospam command on logout

### ISSUE THREAD

**Issue by IanWPG** [pop4959/LWCX#16]
**LWC Version (/lwc admin version):** 

===2.1.5-09ad392

**Server version (/version):** 

===git-Paper-162

**Short five word summary of issue:** 

===Persist nospam command on logout/in

**Detailed description of problem:**

===Would like it if possible to toggle on /lwc:cnospam even after logging out and back in.

**If there was an error in console, put it here:**
``` N/A
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
@IanWPG Thank you for the suggestion. I will take a look and see if this is possible. Are you sure it disables itself when you log out, or is it only when the server is stopped?

On an unrelated note, the version you are using is fairly out of date. Please ensure you update to LWCX, as I am no longer updating/maintaining Modern LWC. You can find the latest version [here](https://www.spigotmc.org/resources/lwc-extended.69551/).

**Comment by IanWPG** [comment]
Thanks, I was not aware of a newer version. I will update asap. To answer
your question server stays on user shuts down there client minecraft or
simply disconnecting and rejoining it forgets you entered the command
cnospam.

**Comment by pop4959** [comment]
Ok, that is what I thought you meant. Was just making sure as not to be ambiguous. Have you considered also using the options in core.yml for choosing not to show notifications to the user?

**Comment by IanWPG** [comment]
> Ok, that is what I thought you meant. Was just making sure as not to be ambiguous. Have you considered also using the options in core.yml for choosing not to show notifications to the user?

Are you referring to 

"    showNotices: true"

or

"protections:
    denyRedstone: false
    denyHoppers: false
    autoRegister: false
    ignoreBlockDestruction: false
    ignoreLeftClick: false
    ignoreRightClick: false
    ignoreExplosions: false
    allowEntityBreakDoor: false
    allowEntityInteract: false
    quiet: false
"

The quiet false to true?

**Comment by pop4959** [comment]
Yeah I was just making sure there isn't already something that covers this. It looks like quiet is the option you might be searching for. Check out the [wiki here for descriptions of the options](https://github.com/pop4959/LWCX/wiki/Configuration#protections), since it appears the comments have been stripped out of yours. Let me know if you found what you need.

**Comment by IanWPG** [comment]
showNotices: true to false seems to have done the trick, luckily still shows notices for when you attempt to access someone else's locked chest so bonus :) Sadly hitting your own* chest no longer tells you if its locked or not downside.

quiet: false to true has the same effect with the same downside. I will live with this, will be happy to not see this chest is locked by blah a billion times lol. Feature request for the future retain left clicking (attacking) your* chest will still display information on locked status and normal right clicking actions display no messages upon opening a chest.

PS. Updated to LWCX-2.1.8

**Comment by pop4959** [comment]
Glad you found something that works for you. Keep in mind users may still use /cinfo to view protections (with much more information than would be shown in the notification prompt).
