### ISSUE TITLE
Droptransfer mode toggle: problem with double activation

### ISSUE THREAD

**Issue by RedstoneFuture** [pop4959/LWCX#163]
**LWC Version (/lwc admin version):**  2.2.7 #ad0f824
**Server version (/version):** 1..16.5 PaperMC #589

**Short five word summary of issue:** 

If I activate the Droptransfer mode with `/lwc mode droptransfer on` twice times, the deactivation command (`/lwc mode droptransfer off`) will down't deactivate with the first time.

**Detailed description of problem:**

![grafik](https://user-images.githubusercontent.com/4140635/124390431-e3ab1f00-dceb-11eb-9b0e-5e810545d380.png)

Here, a demonstration video: in 0:19 I activate the Droptransfer  mode twice times, and then I deactivate it. The first deactivation will not work. (Status and drop behavior is synchronous, so the status message is displaying the correctly drop status.)

https://redstoneworld.de/videos/intern/lwcx_droptransfer.mp4

**If there was an error in console, put it here:**
```
-
```

**Comment by pop4959** [comment]
Closing for now - while I have confirmed this is a real bug but I'm not sure it's worth fixing. With normal usage (turning on and off) this does not happen.

If anyone is still interested in making a fix for this, feel free to open a PR!
