### ISSUE TITLE
PlayerInteractEvent not being cancelled 

### ISSUE THREAD

**Issue by ToeDev** [pop4959/LWCX#167]
**2.2.6-2d10269** 
**git-Paper-529 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)** 

**PlayerInteractEvent not cancelling a trapdoor opening** 

**I'm using the plugin BetonQuest and attempting to cancel the opening of a iron trapdoor(for questing purposes).  The plugin is cancelling the PlayerInteractEvent when I would right click the trapdoor, but this doesn't stop the trapdoor from opening.  What event is called when an iron trapdoor is opened in LWC?  Please let me know if you require more information.**

**Comment by pop4959** [comment]
LWC fires an LWCProtectionInteractEvent which is handled in DoorsModule.

References:

https://github.com/pop4959/LWCX/blob/ad0f824361ffac3c91645aecf1adafdb2b59b018/src/main/java/com/griefcraft/scripting/event/LWCProtectionInteractEvent.java

https://github.com/pop4959/LWCX/blob/master/src/main/java/com/griefcraft/modules/doors/DoorsModule.java

You can also disable this functionality in doors.yml.

**Comment by ToeDev** [comment]
What line of code or event triggers the LWCProtectionInteractEvent?  To cancel the trapdoor being opened, that first triggered event would need to be cancelled i believe.

I'm looking to do this on only a few doors and not all of the iron trapdoors sadly.

**Comment by pop4959** [comment]
Searching through the [usages of this event](https://github.com/pop4959/LWCX/search?p=2&q=LWCProtectionInteractEvent) you can see that it is fired from [here](https://github.com/pop4959/LWCX/blob/ad0f824361ffac3c91645aecf1adafdb2b59b018/src/main/java/com/griefcraft/listeners/LWCPlayerListener.java#L645) in the circumstance you most care about.
