### ISSUE TITLE
Feature request - prevent magnet chests from picking up items with a long pickup delay

### ISSUE THREAD

**Issue by yummiesttag** [pop4959/LWCX#17]
To enable or disable the sucking in of invincible or nonpickupable items?

**Comment by pop4959** [comment]
Yup, thanks for making the issue. For anyone else reading this, most of the issue was discussed on Discord. To clarify, this is a suggestion to add an option to the magnet module not to pick up "special" items such as those generated by other plugins that are not meant to be picked up.

**Comment by pop4959** [comment]
@yummiesttag Can you try the latest development build? I added a new option that should appear in your magnet.yml file next time you restart your server called "maxPickupDelay" (vanilla default: 40). It should prevent LWC from picking up items that don't have natural values (such as those from plugins). Please test and let me know if it's working for you.

**Comment by pop4959** [comment]
Heard back on Discord and it sounds like this is working well.
