### ISSUE TITLE
Towny compatibility not working

### ISSUE THREAD

**Issue by gecko10000** [pop4959/LWCX#170]
**LWC Version (/lwc admin version):** `Main plugin: 2.2.7-ad0f824/`
**Server version (/version):**
```
[02:05:28 INFO]: Checking version, please wait...
[02:05:28 INFO]: This server is running Purpur version git-Purpur-1374 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8250199 on ver/1.17.1)
```

**Short five word summary of issue:** Players can lock containers in town chunks.

**Detailed description of problem:**
When a town is claimed, outsiders (who do not have permission to build/break/switch/itemuse, the four main permissions) can `/lock` a container within the town.

To recreate this, create a server with Towny and LWC. Have a player create a town and place down a container (making sure it's not locked). Have another player who does not have any permissions in the town (which by default they will not) `/lock` the container.

**Comment by pop4959** [comment]
I haven't seen any other reports of this bug so I'm going to assume it's your plugins or something else.
