### ISSUE TITLE
Suggestion: Private limits per world

### ISSUE THREAD

**Issue by ehetteNandaYo** [pop4959/LWCX#172]
**Short five word summary of issue:** 

Private limits per world

**Detailed description of problem:**

It would be great if the permission nodes worked per world, or a setting to count the limits per world

So if I set a private in the overworld it doesnt affect the limit in the nether world

Example:
I give a  group permission limited to a world to give max 10 privates in overworld and 5 privates in the nether

If a player has 10 privates set in overworld he could still place 5 more privates in the nether.

**Comment by dlee13** [comment]
My server has main worlds and resource worlds by using multiverse, and it would be great to be able to set the limits in my resource worlds to 0.

**Comment by pop4959** [comment]
> My server has main worlds and resource worlds by using multiverse, and it would be great to be able to set the limits in my resource worlds to 0.

@dlee13 In your specific case you probably don't need to use limits; simply set the `lwc.protect` permission to false in your other world to make it so that players cannot make or manage protections there.

**Comment by pop4959** [comment]
I don't plan on working on this, although if someone else does feel free to make a PR!

I'm pretty sure this can be done with permission contexts as well, if this is still relevant to you.
