### ISSUE TITLE
Player name on /cinfo

### ISSUE THREAD

**Issue by GhebyFelix** [pop4959/LWCX#173]
**LWC Version (/lwc admin version):** 2.2.7-ad0f824/
**Server version (/version):** 1.17.1

**Short five word summary of issue:**  player name on /cinfo

**Detailed description of problem:**

hi i would like to remove the (32452l23-32fsef432........) from name  when i type /cinfo  and if its possible to change the color of players name from yellow to anything else
https://ibb.co/w4XGWYT there is a link to how its look the issue

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Just went ahead and added this. Download the latest dev build and use the `%name%` placeholder instead of `%owner%`.
