### ISSUE TITLE
placeholder list/ add placeholder

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [pop4959/LWCX#174]
**LWC Version (/lwc admin version):**  not relevant
**Server version (/version):**  not relevant

**Short five word summary of issue:** add placeholder list to wiki

**Detailed description of problem:** In the locale section of the wiki, you should add all the available placeholders.

*also add %owner% for the "This chest is locked by a magical spell" message, so it can be configged to say "This chest is locked by [user]."*

**If there was an error in console, put it here:**
```nope
<paste it here between the little tick marks>
```nope

**Comment by pop4959** [comment]
Refer to the official translation files for valid placeholders - they are defined per message.
