### ISSUE TITLE
%lightblue%

### ISSUE THREAD

**Issue by P-Gabor** [pop4959/LWCX#175]
LWC Version (/lwc admin version): LWC Expanded 2.2.7
Server version (/version): 1.17.1
Short five word summary of issue: %lightblue% in texts
Detailed description of problem:
After for example executing /lwc:lwc, the text showing up contains %lightblue% in front of some words/phrases.

If there was an error in console, put it here:

![lwclwc](https://user-images.githubusercontent.com/92330610/136834626-0b44b2d3-1575-4961-93ab-d3c672a9cb2c.png)

**Comment by pop4959** [comment]
Not a bug. Looks like you most likely have an outdated custom locale file on your server. Color codes were changed several years ago in the default locales to match existing standards for how they should be named.

For a list of valid color names, check [here](https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes) on the Minecraft Wiki.

For example, `%lightblue%` is probably supposed to be `%aqua%`.
