### ISSUE TITLE
Enhancement: Option to prevent villagers from considering protected job site blocks

### ISSUE THREAD

**Issue by kccricket** [pop4959/LWCX#177]
Enhancement suggestion:

Provide a protection flag that controls whether or not an unemployed villager can use the protected block to gain a profession. Optimally, nearby villagers wouldn't consider the protected block to be available for gaining a profession from (i.e. villagers wouldn't path toward it as if they could gain a profession from it).

And of course all the configuration options and permission nodes that would normally go with a flag.

**Comment by pop4959** [comment]
Doesn't seem like there is much interest for this. Not sure if we need another flag for it.
