### ISSUE TITLE
Enhancement: Allow users to toggle auto-locking for themselves

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [pop4959/LWCX#181]
**LWC Version (/lwc admin version):** 
![image](https://user-images.githubusercontent.com/57046530/141209885-ab4f23a6-e7df-4fdf-a2fa-342114691e38.png)
**Server version (/version):** 
![image](https://user-images.githubusercontent.com/57046530/141209909-19e33c77-59cd-46fe-8ccf-23d4823a8fbf.png)
**Short five word summary of issue:** 
Allow toggling auto-lock individually
**Detailed description of problem:**
Idk like /ctoggle to toggle automatically locking things

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
You can use `/lwc mode nolock` to toggle automatic locking temporarily.
