### ISSUE TITLE
LWCProtectionRegisterEvent not being called on auto register

### ISSUE THREAD

**Issue by snowgears** [pop4959/LWCX#184]
**LWC Version (/lwc admin version):** 
LWC 2.2.7 
**Server version (/version):**
Spigot 1.17.1

**Short five word summary of issue:** 
LWCProtectionRegisterEvent not being called on auto register

**Detailed description of problem:**
Hooked into the plugin. Able to access LWC protections just fine and listener is able to listen to all other events as well. LWCProtectionRegisterEvent is never called when placing down chests even though "Private chest registered" is displayed in game.

**Comment by snowgears** [comment]
More info: https://www.spigotmc.org/threads/events-not-being-called.537700/

**Comment by pop4959** [comment]
LWC has its own module system (which dates back before Bukkit's event system as far as I know). You need to create a java module, add your events there, and then register your module with the module loader (not Bukkit).

[LWCTrust](https://github.com/pop4959/LWCTrust) is a simple example which shows how to accomplish this. If you still have any questions feel free to drop by the Discord server and share your code.
