### ISSUE TITLE
Lock player head breaks when is water placed under it.

### ISSUE THREAD

**Issue by RispyCZ** [pop4959/LWCX#185]
**LWC Version (/lwc admin version):** 
2.2.8-dev-52b334e
**Server version (/version):** 
Paper 1.18.1
**Short five word summary of issue:** 
When I lock player head and then place water on block under it breaks.

**Comment by pop4959** [comment]
This is a bug, however I'm unlikely to get around to fixing this one. [Bolt](https://github.com/pop4959/Bolt/wiki) already supports player heads and does not have this issue, so if this is still a problem for you I'd recommend migrating to that instead (which supports all of the same basic features that LWC does).

If anyone does want to make a PR to fix this, be welcome.
