### ISSUE TITLE
Potential ChestSort compatibility?

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#188]
Would you be willing to add some ChestSort compatibility?
Regarding: https://github.com/JEFF-Media-GbR/ChestSort/issues/151

**Comment by pop4959** [comment]
Hi, I cannot possibly add support for all 3rd party plugins. There's the LWC API that can be used to interact with protections, or prevent them from being accessed improperly, etc: https://github.com/pop4959/LWCX/wiki/Developers

If you need other plugins to get LWC integration, send them this link :) Feel free to reopen this issue if there's any further questions, but as said - I cannot look into all 3rd party plugins, they are advised to use the LWC API instead :)

**PS:** I want to make it explicitly clear that I don't intend to mock the developer of ChestSort with that, but it is pretty much the same response I would give anyway but rehashed so thought it would be more comedic to borrow his words. API for access checking in LWC and other popular protection plugins are standard, and ideally his plugin would provide built-in hooks for these. On the other hand, it's not very feasible for LWC or other popular protection plugins to add hooks for every plugin that breaks or bypasses protection access, when again, there is a readily available API for that to ensure that plugins like ChestSort never even attempts to bypass them in the first place.

Your best option at this point if ChestSort doesn't intend to add protection support would be to write a bridging plugin, using both the LWC and ChestSort APIs.

**Comment by andrewkm** [comment]
Bridge plugin it is.
I had to try right lol :P
