### ISSUE TITLE
Suggestion: Transferring All Locks

### ISSUE THREAD

**Issue by melaniebeedot** [pop4959/LWCX#189]
**LWC Version (/lwc admin version):** 2.2.7-ad0f824
**Server version (/version):** 1.18.2

**Short five word summary of issue:** transferring all locks to someone

**Detailed description of problem:**It's not so much a problem as an inconvenience: if a player is leaving the server or had to get a new account and needs to transfer all their stuff to someone else, having to /lwc admin forceowner <username> each locked item individually, or purging all the player's locks and having the new player re /lock everything (even with /cpersist it can take a long time to find and click all chests, etc.)

I was thinking, if possible, maybe you could implement a /lwc admin forceownerALL <username> so we could transfer ALL of a player's locks to a new player all at once?

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
There already exists an `/lwc  admin forceownerall` command (named exactly that). Please see the [wiki](https://github.com/pop4959/LWCX/wiki/Commands#admin-access) for more information.
