### ISSUE TITLE
Suggestion: cmodifyall

### ISSUE THREAD

**Issue by melaniebeedot** [pop4959/LWCX#190]
**LWC Version (/lwc admin version):** 2.2.7-ad0f824
**Server version (/version):** 1.18.2

**Short five word summary of issue:** cmodify all existing locks simultaneously

**Detailed description of problem:**It's not so much a problem as an inconvenience: if a player wants to share all their stuff with another player, they have to /cmodify all of their locks individually (even with /cpersist it can take a long time to find and click all chests, etc.)

I was thinking, if possible, maybe you could implement a /cmodifyALL so we could modify ALL of a player's locks to include another player all at once?

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
This will not be added directly to LWC due to how everything works internally. You can, however, use a plugin such as the [LWC Trust](https://www.spigotmc.org/resources/lwc-trust.75580/) addon to allow players to grant access to all of their protections to another player.
