### ISSUE TITLE
Suggestion: automatic cmodify upon chest placement

### ISSUE THREAD

**Issue by melaniebeedot** [pop4959/LWCX#191]
**LWC Version (/lwc admin version):** 2.2.7-ad0f824
**Server version (/version):** 1.18.2

**Short five word summary of issue:** automatic cmodify upon chest placement

**Detailed description of problem:** One of our players had this idea so I thought I'd submit it for them. We have it set up that chests are automatically /locked upon placement, and they wanted to know if it would be possible to implement something where the player could choose to set all future chests to automatically be /cmodified to their alt account so they don't have to go back and /cmodify each new chest the place as they play?

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
This was implemented as `/cdefault` in a recent development build. Keep in mind that this is a new feature and you will need to update to 2.2.8-dev to access it currently.
