### ISSUE TITLE
Feature-Request: Group as Owner

### ISSUE THREAD

**Issue by JaHollTV** [pop4959/LWCX#195]
Hey,
little feature request to set a Group (for example Luckperms group) as the Owner of a Lock :)

**Comment by pop4959** [comment]
LWC already has support for permission groups, using `group:` (or `g:` for short) on the chest. See the [wiki](https://github.com/pop4959/LWCX/wiki/Commands#protection-creation) for additional details/examples. Keep in mind this is only supported through Vault, so make sure Vault and a compatible permissions plugin is installed (LuckPerms should work just fine).

**Comment by JaHollTV** [comment]
No,
i mean to set the OWNER of a Protection as a group: /lwc admin forceowner g;my_role

**Comment by pop4959** [comment]
Unfortunately that isn't possible as the owner must be a player. Is there any reason why you want the group to be owner and not just on the ACL?
