### ISSUE TITLE
Some texts not translated and no locale file

### ISSUE THREAD

**Issue by Bloodlex** [pop4959/LWCX#201]
**LWC Version (/lwc admin version):** 
2.2.8

**Server version (/version):** 
git-Paper-386 (MC: 1.18.2)

**Short five word summary of issue:** 
Not translated texts in Polish

**Detailed description of problem:**
Some texts are not translated into Polish and no language file is generated in locale directory, which doesn't allow me to even provide my own translation. How does it work? Where this texts come from? Is it stored inside the jar file? How can I provide my own translation then?

Thanks for your help!

**Comment by Bloodlex** [comment]
Already find the answer 🙂

**Comment by pop4959** [comment]
The default Polish translation can be found [here](https://github.com/pop4959/LWCX/blob/master/src/lang/lwc_pl.properties).

It does look like some of the newer stuff is missing. It would be much appreciated if you could contribute some of your translations once you have tested them locally! You can find information about custom locales on the [wiki](https://github.com/pop4959/LWCX/wiki/Custom-Locales).
