### ISSUE TITLE
Add options to reduce "spam" in /climits

### ISSUE THREAD

**Issue by JohOply** [pop4959/LWCX#21]
**Short five word summary of issue:** Add options to reduce "spam" in /climits (or write a limitsv3? :D)

**Detailed description of problem:**

Quote from discussion with pop
> I don't think I can do much about the spam in limits v2 due to how the limits themselves are currently being handled. The closest thing is creating limits groups manually (which I did for shulker boxes because they are very commonly protected and there are a large volume of them). Maybe in the future it can be improved (v3?). I think the one optimization I could probably make is to give an option to skip protections that aren't being used. So if a player is not using their limits yet, or not able to use them (ie. 0/5 or 0/0), it will simply not display in climits. That way the player is only looking at limits that are apparent/relevant to them. I am willing to look into other options but I will say that it is rather difficult to change the current system dramatically.

**Comment by pop4959** [comment]
I don't plan on completely rewriting limits right now but options/groups can definitely be added to make it a bit better.

**Comment by pop4959** [comment]
Implemented an option in c5aea0afc93044d51b9715d9c9e44746f12cbb72 which hides empty limits. This should reduce most of the spam coming from setting limits (especially in permission hierarchies) to zero.

The new option is called `limits.showEmpty` and is found in limitsv2.yml. If you don't see it, simply start the server with the new dev build and it should show up. Setting the option to false will cause empty limits not to display anymore.
