### ISSUE TITLE
No lock mode diables possebilty to use the /lock comand 

### ISSUE THREAD

**Issue by Enderbonbon** [pop4959/LWCX#211]
**LWC Version :LWC Extended 2.2.8** 
**Server version:Spigot 1.19.2** 

**Short five word summary of issue:** 
User No lock mode not working

**Detailed description of problem:**
If you enable the user mode "No Lock Mode" (/lwc mode nolock) no locks are created automatically.
At the same time you can´t use /lock to lock e.g. a chest anymore. There are no messages in the chat or server console and if you try /cinfo the chest has no lock on it. 

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Can confirm this is an issue - not necessarily a bug though. Looks like this is how it's always worked in LWC.

To lock chests again, toggle no lock off.
