### ISSUE TITLE
MariaDB 11 Breaking Changes

### ISSUE THREAD

**Issue by DarkArc** [pop4959/LWCX#220]
There's a breakage in MariaDB 11 where `transaction_isolation` is not supported. This is not directly caused by LWC, but LWC experiences it as it uses the mysql connector bundled with Spigot/Paper in mysql mode.

There are two ways I'm aware of to fix this:
- Allow jdbc urls to be specified in the configuration file, and then have users install the mariadb jar in the `<server root>/libraries` directory (or automate this)
- Shade and relocate the appropriate driver files with LWC itself (e.g., https://github.com/packet-loss-gaming/Grindstone/commit/64517e64bf1eb386af6985afa53c77e36aaa7a03 -- LWC would need something a bit more complicated as it would need to shade and relocate both the mariadb and mysql drivers, and then pick which one to load based on the configuration)

**Comment by DarkArc** [comment]
https://github.com/LogBlock/LogBlock/issues/868 is another example of this problem manifesting.

**Comment by pop4959** [comment]
Is this an issue with every Bukkit plugin? If so it might be worth reporting upstream (Spigot, Paper).

**Comment by DarkArc** [comment]
Issue opened as requested.
