### ISSUE TITLE
Iron (trap)doors

### ISSUE THREAD

**Issue by PHUEE** [pop4959/LWCX#221]
**LWC Version (/lwc admin version):2.3.0
**Server version (/version):1.20.1

**Short five word summary of issue: Iron lock doors don't open

**Detailed description of problem:**
If you lock iron doors (or iron trapdoor) you can't open them.

**If there was an error in console, put it here:**
```
```

**Comment by pop4959** [comment]
Locked iron doors are not openable by default. You can enable this in `doors.yml`.

I am able to open them just fine with the option enabled.
