### ISSUE TITLE
[BUG] lwc.mod doesn't work with donation-protection

### ISSUE THREAD

**Issue by JaHollTV** [pop4959/LWCX#224]
**LWC Version (/lwc admin version):**  latest: https://www.spigotmc.org/resources/lwc-extended.69551/ | Main plugin: **2.3.1**/ 
**Server version (/version):**  git-Paper-81 (MC: 1.20.1)

**Short five word summary of issue:** 
lwc.mod doesn't work with donation-protection

**Detailed description of problem:**
With the lwc.mod permission you can place and take items from normal protections. Everything works.
Only a donation-protection can not be modified: you cannot take items out of a chest.

**If there was an error in console, put it here:** no error

**Comment by pop4959** [comment]
Fixed in fa8ca3ff76b6f9ca0c4891b6f0000f053975b398.
