### ISSUE TITLE
LWC /lock not working on new 

### ISSUE THREAD

**Issue by BboyZeroOne** [pop4959/LWCX#225]
**LWC Version (/lwc admin version):** 2.3.1
**Server version (/version):** 1.20.1 git-Paper-196

**Short five word summary of issue:** 
/lock does not work on new blocks.

**Detailed description of problem:**

/lock and /cprivate does not work on Mangrove, Bamboo and Cherry tree doors/trapdoors/gates etc.

Video: https://drive.google.com/file/d/1l-KwCOovKtCPfpP9_kiWqLqINtb1vNyF/view?usp=sharing

**If there was an error in console, put it here:** 
```
None
```

**Comment by pop4959** [comment]
The configuration is not auto updated, you will need to add those blocks.

Generate a new config or refer to the config file [here](https://github.com/pop4959/LWCX/blob/master/src/main/resources/config/core.yml) for changes.
