### ISSUE TITLE
Entities lost protections post update

### ISSUE THREAD

**Issue by Doctacosa** [pop4959/LWCX#235]
**LWC Version (/lwc admin version):** 2.3.2
**Server version (/version):** This server is running Paper version 1.20.6-137-master@bd5867a (2024-06-04T21:04:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Short five word summary of issue:** Entities lost protections post update

**Detailed description of problem:**

We've updated from Minecraft 1.20.4 to .6 over the weekend. LWC has reported no errors during the update, and block protections seem to be just fine.

However, we have multiple entities that are no longer protected. Multiple item frames and armor stands are no longer flagged with anything, but others in the same world are still fine. People can access them freely and `/cinfo` says they aren't registered. Looking at the lwc.db file data reveals no missing records. Is it possible that something about coordinates changed ever so slightly, affecting how entities are covered?

**If there was an error in console, put it here:**
```
No errors!
```

**Comment by pop4959** [comment]
Entity protections have been completely unsupported, undocumented, and generally "use at your own risk" for at least 3 years, and discouraged from use with limited support years before that. I would recommend either not using LWC for entity protections, or use a plugin that supports them properly such as Bolt, which has [an easy migration path](https://github.com/pop4959/Bolt/wiki#migration-for-lwc-users) from LWC (and back if something doesn't work).

Aside from that, my hint here is that this probably has something to do with entity names changing in the update. It's not unlikely that you can fix this yourself in the DB if you must, but I have not tested this.

**Comment by Doctacosa** [comment]
Gotcha, I must have been the memo about the feature being unsupported. Thanks for the reply, I'll see what I can do on this.

**Comment by pop4959** [comment]
No worries, thanks for understanding. If you need any more help feel free to stop by the Discord support channel and we can talk more.
