### ISSUE TITLE
New door protections do not work 1.21

### ISSUE THREAD

**Issue by Mundo-Minecraft** [pop4959/LWCX#236]
**LWC Version (/lwc admin version):** 

-the latest version #18 (Sun May 19 21:12:04 UTC 2024)

**Server version (/version):** 

-the latest version build #107

**Short five word summary of issue:** 

-new door protections do not work

**Detailed description of problem:**

The protection of the copper doors and trapdoor does not work correctly. They are added to the config, you protect a copper door and the plugin indicates that it is protected. But if you open and close the message indicating the protection no longer appears. In addition to being able to break the block under the door and stop having protection. .
protections that fail: https://pastebin.com/MLNSY74G

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

-there are no errors in console

**Comment by pop4959** [comment]
Updated in 84b0e9067fc4008bf0dc8a53fc69968f2345080c
