### ISSUE TITLE
/lwctrust addon

### ISSUE THREAD

**Issue by OverlordFreddo** [pop4959/LWCX#24]
**Short five word summary of suggestion/enhancement:** 

A command to allow someone you nominate access to all the protections you'll ever make.

**Detailed description of enhancement/suggestion:**

Commands:
`/lwctrust add [player]` Adds someone to your list of trusted players
Output: displays a warning ands ask you to confirm your action

`/lwctrust remove [player] Removes someone from your list of trusted players
Output: displays a message that you've removed someone from your list of trusted players.

`/lwctrust list` Lists your trusted players
Output:
displays a list of players currently trusted OR "You currently trust no-one"

`/lwctrust confirm` Confirm your previous action - as this feature could be abused.

**Comment by pop4959** [comment]
I'm not sure if universally adding people to protections is a good idea or not but I'll leave this open to think about for now. At the very least the confirmation is possibly a way to handle it better.

**Comment by OverlordFreddo** [comment]
Perhaps there could be a short reminder when the person logs in also?

**Comment by JohOply** [comment]
I think it could be really useful for some people which share everything in game (I have some of them on my server)

**Comment by toeffe** [comment]
This would be such a welcomed feature! :)
It is really a hassle unlocking chests, playing with multiple people. Having to use persist, Then proceed to use modify. Allowing everyone in a group to access said chests.

**Comment by xFrann** [comment]
Would love to see this soon enough!

**Comment by OverlordFreddo** [comment]
So how many votes does this need to properly be considered a planned feature/addon in future?

**Comment by pop4959** [comment]
@OverlordFreddo @JohOply @toeffe @xFrann

So, I've decided against including this in the plugin itself for various reasons, but it is available on Spigot as an add-on, similar to economy and keys. Please visit the corresponding plugin page for additional information. All further discussion should be on that plugin's discussion page, or GitHub.

I hope that you all will like it. If there is anything missing that you'd like to see, consider making a feature request. Likewise, report any bugs that you find and I'll gladly look into them. Also consider making a donation or send me a nice message if this makes a big difference for your server. It did take me a considerable few hours to develop this, of my free time. Thanks!

LWC Trust: <https://www.spigotmc.org/resources/lwc-trust.75580/>
LWC Trust Discussion: <https://www.spigotmc.org/threads/lwc-trust.419930/>
LWC Trust GitHub: <https://github.com/pop4959/LWCTrust>
LWC Trust Discord: <https://discord.gg/PHpuzZS>

**Comment by OverlordFreddo** [comment]
You're amazing. That is all.
