### ISSUE TITLE
Error when sending command

### ISSUE THREAD

**Issue by syokkendesuyo** [pop4959/LWCX#30]
**LWC Version (/lwc admin version):** 
- LWCX 2.2.0 (1708efe)

**Server version (/version):** 
- git-Spigot-1a3504a-dfa7583 (MC: 1.13.2)

**Short five word summary of issue:** 
Error when sending command

**Detailed description of problem:**
`That isn't a valid LWC command.` is displayed when command is sent.

`/lwc -c` or `/lwc create`

**If there was an error in console, put it here:**
```
none
```
![image](https://user-images.githubusercontent.com/5967134/63369813-b6854a00-c3bb-11e9-8d46-4200dfb23d9e.png)

**Problem location:**
- [CreateModule.java L214](https://github.com/pop4959/LWCX/blob/634f8608151043845e004900958b931de51021f9/src/main/java/com/griefcraft/modules/create/CreateModule.java#L214)
- [CreateModule.java L214](https://github.com/pop4959/LWCX/blob/634f8608151043845e004900958b931de51021f9/src/main/java/com/griefcraft/modules/create/CreateModule.java#L250)

**Comment by pop4959** [comment]
Should be fixed by 697d3d4fa0f91834027d119c0f867bb72e38c02d.
