### ISSUE TITLE
Kindly allow user config of "...is locked with a magical spell" message

### ISSUE THREAD

**Issue by gmalone** [pop4959/LWCX#33]
**LWC Version (/lwc admin version):** 
[02:51:59 INFO]: https://www.spigotmc.org/resources/lwc-extended.69551/
[02:51:59 INFO]: Main plugin: 2.2.1-dev-697d3d4/

**Server version (/version):** 
[02:31:17 INFO]: This server is running Paper version git-Paper-171 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
Allow config of 'locked' message

**Detailed description of problem:**
When a player attempts to use a /cprivate locked block, like a door, a red actionbar message states "The Spruce Door is locked with a magical spell"

That message really needs to be configurable by the server admin to fit the style of the server.

Thanks for keeping LWCX alive and thriving!

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Have you tried modifying the locale as described on the wiki? I believe the key for the message you are trying to edit is named "protection.general.locked.private".

Relevant wiki page: https://github.com/pop4959/LWCX/wiki/Custom-Locales

**Comment by pop4959** [comment]
Appears as if this issue is resolved (see Spigot resource discussion page).
