### ISSUE TITLE
Donation chest flag to only allow certain groups to view/place items in.

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#38]
Donation chest flag to only allow certain groups to view/place items in.
As per our Discord convo @pop4959 :)

**Comment by andrewkm** [comment]
Any updates on this @pop4959 💃

**Comment by pop4959** [comment]
Flags act as an on/off switch, so it's not easily possible to make it work for specific groups, etc. What makes more sense here is if adding the user/group to the chest did this, but this is in direct conflict with #41 (also your issue coincidentally).

**Comment by pop4959** [comment]
Closing this due to lack of response, and in favour of the other issue you have. Fixing the bug there should technically allow for group access normally using the `g:<group>` option in `/cmodify`. I'll see if I can find time to investigate this soon -- admittedly it has been a while.
