### ISSUE TITLE
Adding user to donation chest prevents doesn't allow them to take things out.

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#41]
Users cmodified to donation chests should be able to remove from them.
Currently this is broken.

**Comment by pop4959** [comment]
It looks like this isn't a new bug, but indeed players with access should be able to modify the chest.

Currently a workaround is to use `/cmodify @<player>` to make them chest admin, which will in turn still allow them to take from the chest. However, they will then also be able to add other users to the chest.
