### ISSUE TITLE
[Addon] Make a option to disable "lwc.protect" as default/base permission.

### ISSUE THREAD

**Issue by Remski01** [pop4959/LWCX#42]
Add a option in the config to disable the permission "lwc.protect" as a default permission, this way its not needed anymore to disable it with the permission plugin.

**Comment by pop4959** [comment]
I don't think it's possible to do this, nor does it make sense to add. You can disable lwc.protect as a default permission by negating it (or setting to false) in your permission plugin. Nothing more should be necessary.
