### ISSUE TITLE
Hoppers steal items from other players chests regardless of flags on protections.

### ISSUE THREAD

**Issue by Speyrow** [pop4959/LWCX#46]
**LWC Version: 2.1.5-09ad392**
**Server version: Paper(175) 1.14.4-R0.1-SNAPSHOT** 

**Hoppers steal items from chests** 

**Regardless of any /lwc flag hopper option, when placing a hopper under a chest even if it's protected, a player can steal from another players chest. I'm not 100% sure if it's an incompatibility between our hopper plugin and LWC.**

**Hopper plugin: epichoppers-4.2.9**

**Comment by pop4959** [comment]
First of all, I would recommend updating the plugin. The new plugin page is [here](https://www.spigotmc.org/resources/lwc-extended.69551/) and has updates 2.1.6 and onward.

The other thing you should check is if `disable-move-event` is enabled in paper.yml. This option is known to cause issues with protection plugins.

**Comment by pop4959** [comment]
@Speyrow Any updates?

**Comment by Speyrow** [comment]
It seems as though it's fixed the issue, sorry for not getting back to you! Have a good day!

**Comment by pop4959** [comment]
It's alright, people forget. Glad I was able to help! :smile:
