### ISSUE TITLE
How to remove notices

### ISSUE THREAD

**Issue by AGudChristianBoy** [pop4959/LWCX#49]
2.1.4
1.14.2

remove notices

how to remove notices when you open the chest like when it says this chest is protected by you

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
You're an entire 8 updates out of date. You should download the latest version from [here](https://www.spigotmc.org/resources/lwc-extended.69551/).

Configuration help can be found [here](https://github.com/pop4959/LWCX/wiki/Configuration). In particular, settings for notices are [here](https://github.com/pop4959/LWCX/wiki/Configuration#core).

If you have any further questions, please join the [Discord support server](https://discord.gg/PHpuzZS) and ask in the LWC #support channel.
