### ISSUE TITLE
Error with Orebfuscator

### ISSUE THREAD

**Issue by John-H-Smith** [pop4959/LWCX#56]
**LWC Version (/lwc admin version):** 2.1.3-87f48cb
**Server version (/version):** git-Spigot-56f8471-43183ea

**Short five word summary of issue:** Users can open obrebfuscated chests

**Detailed description of problem:**
While using Orebfuscator (https://github.com/lishid/Orebfuscator/) with Modern LWC, locked chests can be opened if they are orebfuscated.

**Comment by pop4959** [comment]
You're almost 10 updates out of date. Please download the latest version (2.2.3) below, as that might be the issue. There was a bug in the past with Orebfuscator, which the author of said plugin helped to fix. It's likely that you just need to update.

[https://www.spigotmc.org/resources/lwc-extended.69551/](https://www.spigotmc.org/resources/lwc-extended.69551/)

**Comment by John-H-Smith** [comment]
Alright, this works. Thank you!
