### ISSUE TITLE
Dev branch console error.

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#61]
`[18:49:01] [Server thread/ERROR]: [LWC] Plugin LWC v2.2.4-dev-144a91a has failed to register events for class com.griefcraft.modules.pluginsupport.Towny because com/palmergames/bukkit/towny/event/TownUnclaimEvent does not exist.
`

**Comment by pop4959** [comment]
You can safely ignore the error, but I'll fix this in the next build. I was working on something for Towny.

**Comment by pop4959** [comment]
Closing this with 5df7c2edde0cd2f499a8624e7d3b637ac940ee67.
