### ISSUE TITLE
[Feature Request] Command to remove all of a players protections

### ISSUE THREAD

**Issue by jakkuh** [pop4959/LWCX#65]
**LWC Version (/lwc admin version):** 1.9.6
**Server version (/version):** 1.12.2 paper 1618

**Short five word summary of issue:** 
remove all of a players protections
**Detailed description of problem:**
When a player is permanently banned it would be good to be able to easily remove all of their protections as a mod/admin. 

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
This exists already. See [`/lwc admin purge`](https://github.com/pop4959/LWCX/wiki/Commands#admin-commands) and [protection cleanup](https://github.com/pop4959/LWCX/wiki/Protection-cleanup) on the wiki.
