### ISSUE TITLE
Items can be stealed with minecart with hopper

### ISSUE THREAD

**Issue by Miguel-Dorta** [pop4959/LWCX#67]
**LWC Version (/lwc admin version):** 
**Server version (/version):** 
git-Paper-33 (MC: 1.15.1)

**Short five word summary of issue:** 
Steal items with minecart hopper

**Detailed description of problem:**
Items from a protection (eg. chests) can be stealed if a minecart with hopper is placed underneath it. This can be kind of avoided blacklisting all rails, but if the minecart is moved there with pistons or similar, it will steal the items.

**Comment by pop4959** [comment]
Please read #50, and let me know if you still have this issue after double checking that your configuration is correct.
