### ISSUE TITLE
Misleading error message for locking outside of towns

### ISSUE THREAD

**Issue by jakkuh** [pop4959/LWCX#70]
**LWC Version (/lwc admin version):** Dev Build which backported the "locking other peoples town chests" fix to 1.12.2
**Server version (/version):** 1.12.2

**Short five word summary of issue:** 
Misleading error message for locking outside of towns

**Detailed description of problem:**
Also, when someone is denied locking of a chest (like if they are not a member of a town), they're told "You can only protect blocks using LWC inside of a Town!". It seems this is the same error message given when trying to lock a chest in the wilderness and may be a bit confusing to players. 

Maybe this should be changed to "You can only protect blocks using LWC in your own Town!"

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
I fixed this in the latest version of LWC. It might be backported later with other stuff. By the way, you can also create a custom locale to change all messages to your liking (it doesn't really *need* a code change): <https://github.com/pop4959/LWCX/wiki/Custom-Locales>
