### ISSUE TITLE
[Suggestion] Migrate all locks with admin command

### ISSUE THREAD

**Issue by xDeeKay** [pop4959/LWCX#71]
Using `/lwc admin forceowner` becomes a lengthy task when a player has hundreds of locks. I would like to suggest a way to migrate all locks from one username to another with a single command.

**Comment by pop4959** [comment]
`/lwc admin forceownerall`

**Comment by xDeeKay** [comment]
Oh welp, thanks. This should be listed under the command wiki section. Super useful feature I had no idea existed!

**Comment by pop4959** [comment]
Is it not listed? Might need to edit the wiki then.

**Comment by pop4959** [comment]
Fixed. Please let me know (or edit yourself) if you find any other errors in the wiki, as it is mostly copied from the original LWC.

**Comment by xDeeKay** [comment]
Thanks, will do. Just a heads up it's also not listed under the command list when typing /lwc admin

**Comment by pop4959** [comment]
That one might be on purpose because it's kind of a dangerous command to accidentally tab complete (irreversible).
