### ISSUE TITLE
Lock a Bed

### ISSUE THREAD

**Issue by KleinCrafter** [pop4959/LWCX#73]
**LWC Version (/lwc admin version):** 
2.2.4-dev-5df7c2e
**Server version (/version):** 
git-Paper-45 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
**Short five word summary of issue:** 
Bed have two Blocks to lock.

**Detailed description of problem:**
Add Beds to the config
Restartet the Server
`/cprivate` and Interact with the Bed -> Success
`/cinfo` Bock locked
`/cinfo` to the other part of the Bed -> not Locked

**Comment by pop4959** [comment]
Yeah, I don't think LWC currently fully supports beds (and a few other "blocks" that consist of several parts). Although, it does make sense that you should be able to. I'll look into adding this.

Just out of curiosity, what are you looking to lock beds for?

**Comment by KleinCrafter** [comment]
I use beds for a Home Plugin.
One Bed can hold multiple homes, destroying a bed deleted all homes registered to it.

**Comment by pop4959** [comment]
@KleinCrafter Can you download the latest development build and please test to see if it is working? I believe bed protections should be matching correctly now.

**Comment by KleinCrafter** [comment]
Thanks, works fine.
