### ISSUE TITLE
Towny - Town Members Can Lock Chests in Plots They Don't Have Access To

### ISSUE THREAD

**Issue by jakkuh** [pop4959/LWCX#76]
**LWC Version (/lwc admin version):** Dev
**Server version (/version):** 1.15.1

**Short five word summary of issue:** Town Members Can Lock Chests in Plots They Don't Have Access To

**Detailed description of problem:**
The current logic flow for checking if someone should be able to modify protections in a Town is as follows

1. Check if they're a resident. If they are, allow them to create/remove their own protections.
2. If they're not a resident, check if they have Towny DESTROY permissions on that block. If they do, allow them to create/remove their own protections (only in places they have DESTROY permissions, like their own embassy plot in a town they are not a resident of)

This means if you're a resident, you can lock any chests in towns, including chests that are on other users plots.

So I think this logic could be simplified to just check if they have DESTROY permissions, and ignore whether or not they are residents.

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Changed this in the latest development build.
