### ISSUE TITLE
Disable /plot clear

### ISSUE THREAD

**Issue by jordanwilliams1** [pop4959/LWCX#77]
Could you make an option to disable /plot clear, please? I Have my own plugin which will do this and store peoples items from locked chests upon wipe.

**Comment by pop4959** [comment]
Yes this will be added. It has not yet because the Towny features have not been completed. Please use the stable build instead of dev in the meanwhile. Thanks! :smiley:

**Comment by pop4959** [comment]
Should be fixed in aad3c14053bdafe8582c4631d23e42a61cfda534; download the latest dev build. There is a new towny.yml file which includes the configuration for this. The protection cleanup options are disabled by default, but you can enable them if you wish.
