### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#80]
Spigot 1.15.2 (Jenkins 2596)
LWCX 2.2.4

**Description**
Beginning with Spigot 1.15.2 (Jenkins 2596), missing dependency declarations are reported in the log on server start-up as WARN messages.

Reference: https://hub.spigotmc.org/jira/browse/SPIGOT-5546

The relevant log entry is:

`[20:47:28] [Server thread/WARN]: [LWC] Loaded class com.sk89q.worldguard.bukkit.WorldGuardPlugin from WorldGuard v7.0.3-SNAPSHOT;2015-637665f which is not a depend, softdepend or loadbefore of this plugin.`

`[20:47:28] [Server thread/WARN]: [LWC] Loaded class com.sk89q.worldedit.extension.platform.Actor from WorldEdit v7.1.1-SNAPSHOT;4830-33cf4c0 which is not a depend, softdepend or loadbefore of this plugin.`

**Steps to reproduce the behavior**
- Update Spigot to 1.15.2 latest
- Start the server
- Search the log for 'Loaded class

**Expected behavior**
Dependencies should be declared in plugin.yml

**Comment by pop4959** [comment]
Thanks for letting me know, there should indeed be a softdepend for that.

Although, just FYI it looks like the only thing that changed is that Spigot will actively complain about plugins accessing other plugins without declaring it. As far as I can tell, it does not break any of the existing integrations, and they should still be working properly.

**Comment by andrewkm** [comment]
Yup, Spigot made a change and now we’re wildly complaining all over GitHub lmao.

So many plugins are shooting this.

**Comment by pop4959** [comment]
Fixed in 34ef948f49d25ce4c3bcca9632d4b8b5197434df
