### ISSUE TITLE
Doors on top of barrels become locked.

### ISSUE THREAD

**Issue by Helinos** [pop4959/LWCX#82]
**LWC Version (/lwc admin version):** 
2.2.4-52f8c06
**Server version (/version):** 
git-Paper-105 (MC: 1.15.2)
**Short five word summary of issue:** 
Lock ability bypass for doors.

**Detailed description of problem:**
Players are able to lock doors by placing them on top of barrels. This bypasses any limits set on doors and whether or not doors are even set to be lockable.

**Comment by pop4959** [comment]
Can you provide any relevant configuration files (such as your limits)? Also, is the door locked, or the barrel, from your example? I'll try to confirm whether this is a bug asap.

**Comment by Helinos** [comment]
The barrel is locked as our server isn't configured to lock doors.
[configs.zip](https://github.com/pop4959/LWCX/files/4228743/configs.zip)

**Comment by pop4959** [comment]
Should be fixed in the latest dev build via 4acf69e627e0118ad68f3e1727cabd9d6e8cc2cd. If it isn't, let me know and we can re-open this issue.
