### ISSUE TITLE
Player can open others locked chest through mod!

### ISSUE THREAD

**Issue by KoitoTouko** [pop4959/LWCX#83]
**LWC Version (/lwc admin version):** 2.2.4-52f8c06 
**Server version (/version):** git-Paper-243 (MC: 1.14.4)

Player can open others locked chest through this mod!
https://www.curseforge.com/minecraft/mc-mods/block-meter

**Comment by pop4959** [comment]
Join the Discord support server linked on the main plugin page if you want to chat about it. I need more details to consider looking into this.

**Comment by pop4959** [comment]
Closing as this appears to not be an issue with LWCX.

**Comment by pop4959** [comment]
Discussed on Discord; fixed via f7a46be144b12ad983d32e26fe139bf3b1d6a2ab.
