### ISSUE TITLE
Locking buttons doesn't work.

### ISSUE THREAD

**Issue by andrewkm** [pop4959/LWCX#87]
Locking buttons causes them not to work.
Example: https://i.imgur.com/rpGvHRS.png

Make the above setup.
If button isn't locked with LWC, it dispenses stuff from dispenser correctly.
If button is locked with LWC, it won't work, not even for the owner of the button's lock.

Using latest paper/lwc as of this post.

**Comment by pop4959** [comment]
Do both protections have the redstone flag set properly according to your server's config?

**Comment by andrewkm** [comment]
This is our core config:
https://pastebin.com/iQeVnD5H

Am a little confused as to what you are asking.

**Comment by andrewkm** [comment]
All good now :)

**Comment by pop4959** [comment]
Glad to hear, figured that was the issue
