### ISSUE TITLE
Missing translation for charging

### ISSUE THREAD

**Issue by Cretezy** [pop4959/LWCX#88]
**LWC Version (/lwc admin version):** 
`2.2.4-52f8c06`

**Server version (/version):** 
`This server is running Paper version git-Paper-142 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Short five word summary of issue:** 
Missing translation for: `Charged $X for an LWC protection. Thank you.`

**Detailed description of problem:**
The translation isn't found in the translation file.

**Comment by pop4959** [comment]
@lifehome was working on the core economy module rewrite, but it looks like he never got around to adding the economy messages into the locale. This is certainly an issue. Hopefully he's around to improve/fix it soon.

For the time being, perhaps try the [LWCX Economy Plugin](https://www.spigotmc.org/resources/lwcx-economy-plugin.45704/) or [LWCX-EconomicAddon](https://www.spigotmc.org/resources/lwcx-economicaddon-charge-players-for-lwc-protections-mysqlplayerdatabridge-compatible.75752/) which are alternative economy modules. I have not used either, however perhaps they will be useful to you.

**Comment by lifehome** [comment]
Sorry that I wasn't around for the fix, it should be remarked in the codebase that which line should be refactored, I will try to make translation possible asap for this module.

Meanwhile, you are welcome to try out those addon pop4959 just mentioned. :)

**Comment by pop4959** [comment]
Fixed by #89.
