### ISSUE TITLE
"autoRegister: false" setting isn't working

### ISSUE THREAD

**Issue by ShadowCreator250** [pop4959/LWCX#90]
**LWC Version (/lwc admin version): LWCX-2.2.4 
**Server version (/version): CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2)

**Short five word summary of issue: "autoRegister: false" setting isn't working

**Detailed description of problem: 
The setting "autoRegister: false" should prevent locking a.e. a chest when placing it. 
I'm LWC-Admin on my local server and when I place a chest LWC locks it as private in spite of this setting.

(no error in console)

**Comment by pop4959** [comment]
You need to remove the line with "autoRegister" for it to disable. This is a current limitation with the block config. I'll leave this open as an enhancement to remind myself to look into changing this so that invalid protection types count as disabling the option instead of defaulting to private.

**Comment by ShadowCreator250** [comment]
Okay, thx!

**Comment by pop4959** [comment]
Should be fixed in 5d45eaa96694ecfc28e7c7e2c408355711302b49. It'll be included in 2.2.6.
