### ISSUE TITLE
Lecturn read-only support (allow to open lecturn but not taking the book)

### ISSUE THREAD

**Issue by DeStilleGast** [pop4959/LWCX#93]
There is currently no way to protect lecturns (so far I know) to make it read only, in other words: let players read the book but not taking the book

**Comment by pop4959** [comment]
Are you running a recent version of [LWCX](https://www.spigotmc.org/resources/lwc-extended.69551/)? This has been supported already since around the release of MineCraft 1.14.

**Comment by DeStilleGast** [comment]
I downloaded yesteday the latest [Modern LWC](https://www.spigotmc.org/resources/modern-lwc-continuation-of-lwc.2162/) from spigot does that matter ?

**Comment by pop4959** [comment]
Yes it does matter, Modern LWC plugin page died almost a year ago and we moved to LWCX. You're almost 10 updates behind, and that's probably why lectern protections aren't working for you.

**Comment by DeStilleGast** [comment]
Ah, I didnt know that, there is no way to see it and the github page sends me here, that part was confusing, but I will switch plugins and will try again

**Comment by pop4959** [comment]
Yeah the reason for that is because we weren't able to update the plugin page. Apologies for the confusion. If you read the discussion, go to the support links, or download dev builds, they are all now pointing to LWCX.

**Comment by DeStilleGast** [comment]
oke, while you are online, how do I set it up, cprivate deny's to open and cpublic allows to take it away.
In the modern LWC page there are no reviews talking about LWCX

**Comment by DeStilleGast** [comment]
found it, its the command `/cdisplay`

**Comment by pop4959** [comment]
Well, that part is basic LWC. 😄 

private: only accessed by you or people on the access list
public: access by everyone
donation: access to put in by everyone, but not take out
display: access to view, but not put in or take out

For you, both donation and display should work.

Check out the wiki here on GitHub for more information about the plugin! 😃 

Glad to see you figured it out!

**Comment by DeStilleGast** [comment]
Yeah, I only knew cprivate and cpublic and there is nothing in the wiki or I'm looking wrong (I also used the github search but nothing popped up when I searched `lecturn` except this issue page)

**Comment by pop4959** [comment]
Lecterns don't work differently from other blocks with inventories, so there isn't any special note on the wiki.

**Comment by DeStilleGast** [comment]
what about the `/cdisplay` and `/cdonation` command, are they documented or am I just blind 👀

**Comment by pop4959** [comment]
Donation chests are mentioned in the [Getting Started ](https://github.com/pop4959/LWCX/wiki/Getting-Started) guide, but I guess it's missing from the Commands page. I'll try to fix that. Display chests are also new in LWCX so they should probably be added. 😄 The wiki is primarily written by users, so there is sometimes some missing info.

**Comment by DeStilleGast** [comment]
There is nothing mentioning `donation` in the (Getting Started)[https://github.com/pop4959/LWCX/wiki/Getting-Started] on my end 🤔

**Comment by pop4959** [comment]
Oh you're right. It says password, not donation. I misread that, sorry. Good question then! I'll keep this issue open until I'm able to update the wiki.

**Comment by pop4959** [comment]
By the way the strange thing is that donation protections are not new. It's extremely old and I'm surprised I never noticed that it was missing on the wiki. I guess that's obvious to some is not for others.

**Comment by pop4959** [comment]
@DeStilleGast I finally found the time to go ahead and update the wiki. Getting Started page should now have all protection types listed, and the Commands page has also been overhauled (not only to add the two protection types, but everything else should be much more clear and up-to-date). Let me know if you see any problems still, but I'll close this issue now.

**Comment by DeStilleGast** [comment]
Looks good for me, thx for the update 👍
