### ISSUE TITLE
Bulk Item Transfer Kills TPS

### ISSUE THREAD

**Issue by Classicalad** [pop4959/LWCX#96]
**LWC Version (/lwc admin version):**  2.2.5-5b01cd1
**Server version (/version):** 
paper 162 (1.15.2)
**Short five word summary of issue:** 
Mass transferring items destroys performance.
**Detailed description of problem:**
When players use the vanilla method of shift left clicking a stack of items to bring all items from their locked chest to their inventory, it brings our server that maintains 20TPS with 60+ players to under 2 TPS.

https://timings.aikar.co/?id=f8075d59a9b14c0289275e8ea0650935

**If there was an error in console, put it here:**
```
none
```

**Comment by pop4959** [comment]
Mind hopping on the Discord server? I think this will be easier to troubleshoot there. It does look like LWC is lagging on your server, but I don't think it is for the reason you described.

**Comment by pop4959** [comment]
Closing for now, I think we've mostly figured it out on Discord.
