### ISSUE TITLE
Don't want player uuid to show

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [pop4959/LWCX#97]
**LWC Version (/lwc admin version):** 
```
[INFO]: LWC
[INFO]: http://griefcraft.com
[INFO]: Main plugin: 1.9.3/
```

**Server version (/version):** 
```
[INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
```

**Short five word summary of issue:** 
Don't want player uuid

**Detailed description of problem:**
When doing most of LWC player behaviors, the player name is followed by uuid.  
That's pertty useless for a normal player and way too long for display.  
I have `PlayerName (e5b03c7764aa 37+ characters long)`  
I want just `PlayerName`

Didn't find a option in config file or `lwc_en.properties`, can this to be implemented?

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Agreed, it is fairly useless. This has already been changed in LWC for MC 1.13.2-1.15.2 since November 2018. I have back ported this change to the 1.8.8-1.12.2 version for you; it is available here: <https://ci.codemc.io/job/pop4959/job/LWCX-legacy/8/>.

**Comment by mhtvsSFrpHdE** [comment]
@pop4959 I'm updated to `Build #8`, and there were still UUID when query by `/cinfo`  
This is strange, because I've seen the patch source code that should absolutely work.

**Comment by mhtvsSFrpHdE** [comment]
I should grab a minecraft plugin debug and build environment as soon as possible  
to see if I can do more than just asking help...

Do you have any idea about that? IDE... tool chain... etc

**Comment by pop4959** [comment]
It is intended that the UUID displays in `/cinfo`, as the command is meant to show protection information in full - that it also how it works in current versions of LWC. It no longer displays specifically in protection notifications (when clicking chests), and protection modification (with `/cmodify`).

**Comment by mhtvsSFrpHdE** [comment]
@pop4959 Wow, that's really work! Thank you for the patch!
